### PR TITLE
documentation for quantiles and tuple sketch modules

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**
Relevant pull requests (aggregators):
https://github.com/druid-io/druid/pull/5148/
https://github.com/druid-io/druid/pull/5002

### CODE REVIEW

**Comment by fjy** [comment]
👍 This is really helpful

**Comment by b-slim** [comment]
@AlexanderSaydakov thanks!

**Comment by fjy** [comment]
@AlexanderSaydakov all our docs are actually on https://github.com/druid-io/druid

Do you mind submitting there again?

**Comment by gianm** [comment]
Reversion patch in #449. Once the docs are in the main druid-io/druid repo then the release scripts will copy them here, upon next release.

**Comment by gianm** [comment]
I'm working on a patch porting these to the Druid repo.

**Comment by gianm** [comment]
Main Druid repo patch in: https://github.com/druid-io/druid/pull/5513

Thanks @AlexanderSaydakov!

**Pull request merged**
