### PR TITLE
Druid 0.12.0 blog and news post.

### PR DESCRIPTION
**Pull request by gianm**
Whoops, forgot these.

### CODE REVIEW

**Comment by b-slim** [comment]
@gianm does the doc get updated automatically ?

**Comment by gianm** [comment]
@b-slim do you mean the website? Metamarkets used to run a bot that builds `master` when `src` changes. They might still be running it. If not, we can update it manually by doing a build and copying the files over.

**Comment by b-slim** [comment]
@gianm was looking at previous commits like this https://github.com/druid-io/druid-io.github.io/commit/dc5dd7e4406ed76e75c5e793e7567c427464b4c8
 and i see that it contains docs updates as well so was wondering if that need to be done  as well?

**Comment by gianm** [comment]
@b-slim Oh I got what you mean. The doc updates were done on time, about a month ago when 0.12.0 was released. We just collectively forgot to create a news item & blog post.

**Pull request merged**
