### PR TITLE
Fix broken table cells in /docs/latest/operations/metrics.md

### PR DESCRIPTION
**Pull request by shouko**

### CODE REVIEW

**Comment by fjy** [comment]
@shouko this needs to be fixed at https://github.com/apache/incubator-druid

can you resubmit your PR there?

**Comment by shouko** [comment]
@fjy thanks for replying.

It seems that the document at https://github.com/apache/incubator-druid is not broken.

What this PR is trying to fix is the tables on Druid website. http://druid.io/docs/latest/operations/metrics.html

**Comment by gianm** [comment]
Hi @shouko, what @fjy means is that since the Druid website is generated automatically from sources, any modifications should happen over at the sources. The source for this particular file is https://github.com/apache/incubator-druid/blob/master/docs/content/operations/metrics.md.

**Comment by fjy** [comment]
@shouko Closing this for now. Please let us know if you can't find the relevant docs on the main Druid repo.

**Pull request closed without merging**
