### PR TITLE
CSS only changes to add more 'pop' to the site

### PR DESCRIPTION
**Pull request by vogievetsky**
The changes are only to CSS and aim to make the site brighter and more engaging.
One notable change is that on desktop the header will follow you as you scroll.

Compare http://druid.io/ vs https://staging-druid.imply.io/ where the site is deployed for preview.

### CODE REVIEW

**Comment by b-slim** [comment]
@vogievetsky  can you please check http://druid.io/docs/latest/development/extensions-core/druid-kerberos.html
i think it has issue with CSS.

screen shot 2018-11-20 at 4 58 38 pm

**Comment by vogievetsky** [comment]
I am on it

**Comment by vogievetsky** [comment]
it looks like the same problem exited even before this PR

image

(^ I checked out a commit with before this change `f741067918969b922b4e387ff1bfe929012b7c00`)

This PR made it a little more obvious because the ToC is bolded.
Fixing regardless.

**Comment by vogievetsky** [comment]
Fixed here: https://github.com/druid-io/druid-io.github.io/pull/536

**Pull request merged**
