### PR TITLE
Update druid-powered.md

### PR DESCRIPTION
**Pull request by dokia**

### CODE REVIEW

**Comment by fjy** [comment]
@dokia Thanks for the contrib! Great to see Yokou up there

**Comment by fjy** [comment]
@dokia are you part of the Druid China Wechat Group? There is a Druid Beijing meetup coming up that you might be interested in http://www.huodongxing.com/event/4322200984100

**Comment by Hailei** [comment]
@fjy Thanks very much! Our team members  joined the Druid China Wechat Group  yesterday.

**Comment by dokia** [comment]
@fjy Hi fangjin, I did join the wechat group. Thanks for your invation!

**Pull request merged**
