### PR TITLE
fix images in docs

### PR DESCRIPTION
**Pull request by fjy**

### CODE REVIEW

**Comment by himanshug** [comment]
I think, changes here have been reviewed before, so merging.

**Comment by xvrl** [comment]
looks like we changed the rc1 docs to be latest, maybe we can just remove rc1 docs and point to latest.

**Comment by himanshug** [comment]
@xvrl looks like I'm still learning how docs are published :)

(1) It sounds that technically rc1 docs shouldn't be updated and updates made  to rc1/ in this PR should be reverted ... is that right? 
(2) however, for convenience, we can just make rc1 that a symlink pointing to latest ?

**Comment by xvrl** [comment]
no worries @himanshug.
re (1), I don't have very strong feelings, but I prefer if we keep the docs we release in sync with the release tag, unless there's obvious broken links or errors. Regarding the content, that's what we decided to release, so if there's missing stuff we should make sure to include it before the release.

re (2), the _config.yml points to the latest rc/stable version, and we don't publish doc links to anything but stables releases. Everything else should just rely on latest.

**Pull request merged**
