### PR TITLE
Typo fix in historical doc

### PR DESCRIPTION
**Pull request by ak08**

### CODE REVIEW

**Comment by b-slim** [comment]
can you please fill up the druid [CLA](http://druid.io/community/cla.html)

**Comment by b-slim** [comment]
thanks for the contrib!

**Comment by ak08** [comment]
I filled the CLA.
You are welcome.

**Comment by jihoonson** [comment]
Hi @ak08, thank you for the contribution. Druid's documentations are currently maintained in the [source code repository](https://github.com/druid-io/druid). Would you make a new PR for that repository?

**Comment by b-slim** [comment]
@jihoonson thanks i always forget about this...

**Comment by jihoonson** [comment]
@b-slim no problem. 🙂

**Comment by ak08** [comment]
@jihoonson  Done.
https://github.com/druid-io/druid/pull/5753

**Comment by ak08** [comment]
By the way, @jihoonson @b-slim  can this be specified in the Contributing guidelines that the PR needs to be submitted for the main source code repo and not this one?

**Comment by jihoonson** [comment]
@ak08 that's a good point. There is a [guideline](https://github.com/druid-io/druid-io.github.io/blob/src/CONTRIBUTING.md) like below, but it would be better if it can be seen in README as well.

> For any documentation changes (in the "docs" folder), please submit pull requests to the main Druid repo. All Druid documentation is hosted under https://github.com/druid-io/druid/tree/master/docs/content.

**Comment by jihoonson** [comment]
I'm closing this PR.

**Pull request closed without merging**
