### PR TITLE
Added Italiaonline company use cases

### PR DESCRIPTION
**Pull request by enrico-sorcinelli**
The PR adds Italiaonline company use cases

### CODE REVIEW

**Comment by drcrallen** [comment]
Thanks for the contrib! would you mind filling out the CLA at http://druid.io/community/cla.html ?

**Comment by fjy** [comment]
@drcrallen do we need CLAs for ppl adding themselves to powered by page? I thought we agreed Druid webapge doesn't need CLA

**Comment by fjy** [comment]
@drcrallen Druid webpage doesn't even have a license

**Comment by drcrallen** [comment]
That sounds correct, force of habbit

**Comment by drcrallen** [comment]
:+1:

**Comment by enrico-sorcinelli** [comment]
@fjy Thanks!

Regards

**Pull request merged**
