### PR TITLE
Update druid-powered.md

### PR DESCRIPTION
**Pull request by wildmechanix**
Vigiglobe loves Druid as well !

### CODE REVIEW

**Comment by wildmechanix** [comment]
To your demand, here is our contribution as a happy customer of your service.

**Comment by fjy** [comment]
Thanks!!

**Comment by wildmechanix** [comment]
Keep the good work up ! Configuring Druid keeps us busy but we obtain drastic performances ! Thanks to you guys

**Comment by fjy** [comment]
@wildmechanix Happy to help out with looking over your configuration and discussing any other issues at any time :)

**Comment by wildmechanix** [comment]
Thanks, we're having great support from your team already, but we'll keep in touch. Cheers

**Pull request merged**
